# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main


pool:
 name: quiz4abasspool
 demands:
 - msbuild
 - visualstudio
 - vstest


variables:
 buildConfiguration: 'Release'
 solution: '**/*.sln'
 artifactName: 'Abasibiangakequiz4'


steps:
- task: DotNetCoreCLI@2
 displayName: 'Restore NuGet packages'
 inputs:
   command: 'restore'
   projects: '$(solution)'
   feedsToUse: 'select'


- task: DotNetCoreCLI@2
 displayName: 'Build application'
 inputs:
   command: 'build'
   projects: '$(solution)'
   arguments: '--configuration $(buildConfiguration)'


- task: DotNetCoreCLI@2
 displayName: 'Publish application'
 inputs:
   command: 'publish'
   projects: '**/*.csproj'
   publishWebProjects: false
   arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(artifactName)'

